spring:
  config:
    activate:
      on-profile: dev
    import: optional:file:.env[.properties]
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bouquet
    username: bouquet
    password: "like_Lion-bouQuet6^"
  data:
    web:
      pageable:
        one-indexed-parameters: true
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: false
        highlight_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET}
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile

jwt:
  salt: ${JWT_SALT}
  access-token-expired-in: 600
  refresh-token-expired-in: 1209600

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

swagger:
  server-url: https://likelion.patulus.com
  description: "멋쟁이사자처럼 대학 13기 금오공대 교내 해커톤 4팀 API"

springdoc:
  packagesToScan: kr.ac.kumoh.likelion.bouquet
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: /docs
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
  api-docs:
    groups:
      enabled: false
